#! /bin/csh -f

foreach temp (0.728)
  echo " --- temperature ${temp} "  	
  echo " --- temperature ${temp} "  	>> out
  cat > fort.15  <<endofdata
  ibeg  , delt  tmax  tequil nsamp 
   1     0.001  5.   0.00  1 
npart temp rho      rcp  iseed
108   ${temp} 0.8442   2.5  123456
 scale   temp     verlet
 .true.  ${temp}  .true.
iout gr      iout4
33   500000    36
endofdata
 cp lj.res          fort.11
 time  ../Source/MD  >> out
 cp fort.21         lj.res
 mv fort.66         lj.prt
# uncoment if the RDF is calculated
# mv fort.33         lj.rdf
 #perform block analysis
  cp lj.prth fort.31
  mv  lj.prt fort.32
 ../Block/block    >>  out 
# rm fort.*
end
exit








